swagger: "2.0"
info:
  description: "A community website to find and share the best online courses, tutorials and learning paths"
  version: "1.0.0"
  title: "Lunchball Peeps"
host: "localhost:6789"
basePath: "/api"
tags:
- name: "topic"
  description: "Technology Topic"
- name: "course"
  description: "Online Course/Tutorial"
- name: "path"
  description: "Learning Path"
schemes:
- "http"
paths:
  /topics:
    get:
      tags:
      - "topic"
      summary: "Get all topics"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Topic"
    post:
      tags:
      - "topic"
      summary: "Create a new topic"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Topic object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Topic"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Topic"
        405:
          description: "Invalid input"
  /topics/{topicId}:
    get:
      tags:
      - "topic"
      summary: "Get information of a specific topic"
      produces:
      - "application/json"
      parameters:
      - name: "topicId"
        in: "path"
        description: "topic id to get"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Topic"
        400:
          description: "invalid topic id"
        404:
          description: "topic not found"
  /topics/{topicId}/courses:
    get:
      tags:
      - "course"
      summary: "Get courses under a topic"
      description: "Returns an array of courses"
      produces:
      - "application/json"
      parameters:
      - name: "topicId"
        in: "path"
        description: "topic id to get"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Course"
        400:
          description: "invalid topic id"
        404:
          description: "topic not found"
  /courses:
    post:
      tags:
      - "course"
      summary: "Create a course"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Course object to be created"
        required: true
        schema:
          $ref: "#/definitions/Course"
      responses:
        201:
          description: "Course created"
          schema:
            $ref: "#/definitions/Course"
        405:
          description: "Invalid input"
  /courses/{courseId}:
    get:
      tags:
      - "course"
      summary: "Get information of a specific course"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        in: "path"
        description: "course id to get"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Course"
    put:
      tags:
      - "course"
      summary: "Update information of a course (for upvote)"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        in: "path"
        description: "id of the course that needs to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated course object"
        required: true
        schema:
          $ref: "#/definitions/Course"
      responses:
        201:
          description: "Updated"
        404:
          description: "Course not found"
  /topics/{topicId}/paths:
    get:
      tags:
      - "path"
      summary: "Get learning paths under a topic"
      description: "Returns an array of learning paths"
      produces:
      - "application/json"
      parameters:
      - name: "topicId"
        in: "path"
        description: "topic id to get paths"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Path"
        400:
          description: "invalid topic id"
        404:
          description: "topic not found"
  /paths:
    post:
      tags:
      - "path"
      summary: "Create a learning path"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Path object to be created"
        required: true
        schema:
          $ref: "#/definitions/Path"
      responses:
        201:
          description: "Learning path created"
          schema:
            $ref: "#/definitions/Path"
        405:
          description: "Invalid input"
  /paths/{pathId}:
    get:
      tags:
      - "path"
      summary: "Get information of a specific learning path"
      produces:
      - "application/json"
      parameters:
      - name: "pathId"
        in: "path"
        description: "id for path to get"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Path"
    put:
      tags:
      - "path"
      summary: "Update information of a path (for upvote)"
      produces:
      - "application/json"
      parameters:
      - name: "pathId"
        in: "path"
        description: "id of the path that needs to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated path object"
        required: true
        schema:
          $ref: "#/definitions/Path"
      responses:
        201:
          description: "Updated"
        404:
          description: "Path not found"
definitions:
  Course:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      votes:
        type: "integer"
      link:
        type: "string"
      description:
        type: "string"
      difficulty:
        type: "string"
        enum:
        - "BEGINNER"
        - "INTERMEDIATE"
        - "ADVANCED"
      tags:
        type: "array"
        items:
          type: "string"
      topic:
        $ref: "#/definitions/Topic"
  Topic:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
  Path:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      description:
        type: "string"
      votes:
        type: "integer"
      topic:
        $ref: "#/definitions/Topic"
      courses:
        type: "array"
        items:
          $ref: "#/definitions/Course"
externalDocs:
  description: "Find out more about Lunchball Peeps"
  url: "http://lunchball.peeps.io"
