package mySql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import mySql.User;
import mySql.UserRepository;

@Controller //This annotation denotes that this class is a controller class
@RequestMapping(path="/demo")
public class mainController {
    @Autowired //To get the bean called userRepository, auto generated by Spring
    private UserRepository userRepository;

    @GetMapping(path="/add") //Map ONLY GET requests
    public @ResponseBody String addNewUser (@RequestParam String name,
                                             @RequestParam String email){
        /**
         * @ResponseBody -> Returned String is the response, not a view name
         * @ResponseParam -> A parameter from the GET or POST request
         * */
        User user = new User();
        user.setName(name);
        user.setEmail(email);
        userRepository.save(user);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<User> getAllUsers(){
        //returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
