INSERT INTO autolearn.topic VALUES
    (1,'Autodesk Administration'),
    (2,'Python'),
    (3,'JavaScript'),
    (4,'Android Development'),
    (5,'React'),
    (6,'C++'),
    (7,'Java'),
    (8,'Data Structures and Algorithms'),
    (9,'Angular'),
    (10,'HTML 5'),
    (11,'C'),
    (12,'CSS'),
    (13,'Node.js'),
    (14,'Git'),
    (15,'C#'),
    (16,'Bootstrap'),
    (17,'PHP'),
    (18,'MySQL'),
    (19,'Information Security & Ethical Hacking'),
    (20,'Arduino'),
    (21,'Blockchain Programming'),
    (22,'Django'),
    (23,'Unity'),
    (24,'SQL'),
    (25,'Intro to Programming'),
    (26,'MongoDB'),
    (27,'React Native'),
    (28,'Design Patterns'),
    (29,'Vue.js'),
    (30,'ASP.NET'),
    (31,'jQuery'),
    (32,'Raspberry Pi'),
    (33,'Go'),
    (34,'Bitcoin'),
    (35,'Firebase'),
    (36,'Java Spring Framework'),
    (37,'Kotlin'),
    (38,'iOS Swift'),
    (39,'Assembly Language'),
    (40,'Laravel'),
    (41,'Operating Systems'),
    (42,'ECMAScript'),
    (43,'Mathematics For Computer Science'),
    (44,'Web Development');
